basic_app/urls.py
from django.urls import path
from basic_app.views import registration, user_login

app_name = "basic_app"
urlpatterns=[
    path("register/", registration, name="register"),
    path("login/", user_login, name="login"),
]

practicePro/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path("", views.index, name="index"),
    path("", include("basic_app.urls")),
    path('admin/', admin.site.urls),
    path("logout/", views.user_loguot, name="logout"),
]

basic_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.



class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    profile_pic = models.ImageField(upload_to="profile-pic", blank=True)

    def __str__(self):
        return self.user.username


class ProductInfo(models.Model):
    pro_name = models.CharField(max_length=400, blank=False)
    pro_desc = models.CharField(max_length=1000, blank=True)
    pro_pic = models.ImageField(upload_to="product-pics", blank=True)
    pro_price = models.DecimalField(max_digits=5, decimal_places=2)

    def __str__(self):
        return str(self.pro_name) +"  "+ str(self.pro_pic)

basic_app/forms.py
from django import forms
from basic_app.models import ProductInfo, UserProfileInfo
from django.contrib.auth.models import User



class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)


    class Meta():
        model = User
        fields=("first_name","last_name", "username", "email", "password")


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ("profile_pic",)

basic_app/views.py
from django.shortcuts import render
from basic_app.models import ProductInfo
from basic_app.forms import UserForm, UserProfileInfoForm
# Create your views here.


from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required





def index(request):
    product = ProductInfo.objects.all()
    context_dic = {
        "product":product,
    }
    return render(request, "basic_app/index.html", context_dic)


def registration(request):
    user_form = UserForm()
    user_profile = UserProfileInfoForm()
    register = True


    if request.method == "POST":
        user_form = UserForm(request.POST)
        user_profile = UserProfileInfoForm(request.POST)

        if user_form.is_valid() and user_profile.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = user_profile.save(commit=False)
            profile.user=user

            if "profiles-pic" in request.FILES:
                profile.profile_pic=request.FILES["profile-pic"]

            profile.save()
            register = True
        else:
            print(user_form.errors+ "---"+str(user_profile.error))


    context_dic = {
        "user_form":user_form,
        "user_profile":user_profile,
        "register":register,
    }

    return render(request,"basic_app/registration.html",context_dic)


@login_required
def user_loguot(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))


def user_login(request):

    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse("index"))
            else:
                return HttpResponse("Account is not active")
        else:
            print("Someone try to login!")
            print("Username: {} and Password: {}".format(username,password))
            return HttpResponse("Invaild login details")


    else:
        return render(request, "basic_app/login.html")

templates/basic_app/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title></title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static "bootstrap-css/bootstrap.min.css" %}">
        <link rel="stylesheet" href="{% static "css/mystyle.css" %}">
    </head>
    <body>
        <nav class= "navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url "index"%}">
                <strong>Pen</strong>
                <small>.com</small></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url "index"%}">Home <span class="sr-only">(current)</span></a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{% url "admin:index"%}">Admin</a>
                    </li>


                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url "logout"%}">Logout</a>
                        </li>

                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url "basic_app:register"%}">Registration</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="{% url "basic_app:login"%}">Login</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </nav>

        <div class="container">
            {% block content_body %}

            {% endblock %}
        </div>
    </body>
</html>

templates/basic_app/index.html
{% extends "basic_app/base.html" %}

{% block content_body %}

    <div class="col-sm-12 col-md-12 col-lg-12 hidden-xs footer-brand-desktop)">
        {% if product %}
            {% for pro in product %}
                <div class="product_list">
                    {{ pro.pro_name }}
                </div>

            {% endfor %}
        {% else %}
            <h1>No Product Found!</h1>
        {% endif %}
    </div>
{% endblock %}

templates/basic_app/login.html
{% extends "basic_app/base.html" %}

{% block content_body %}
    <div class="jumbotron">
        <h1>Login Here!</h1>
        <form class="" action="{% url "basic_app:login" %}" method="POST">
            {% csrf_token %}
            <label for="username">Username:</label>
            <input type="text" name="username" value="" placeholder="Enter your username">
            <label for="password">Password:</label>
            <input type="password" name="password" value="">

            <input type="submit" name="" value="Login">
        </form>
    </div>
{% endblock %}

templates/basic_app/registration.html
{% extends "basic_app/base.html" %}

{% block content_body %}
    <div class="jumbotron">
        {% if register %}
            <h1>Thank you for regostration.</h1>
        {% else %}
            <form class="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ user_form.as_p }}
                {{ user_profile.as_p }}
                <input type="submit" name="" class="btn btn-primary" value="Sign Up">
            </form>
        {% endif %}
    </div>
{% endblock %}